name: CI
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
      - "TestPlans/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "Package.swift"
      - "Sources/**"
      - "Tests/**"
      - "TestPlans/**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint & Format Check
    runs-on: macOS-26
    env:
      DEVELOPER_DIR: "/Applications/Xcode_26.2.app/Contents/Developer"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install SwiftLint
        run: brew install swiftlint --quiet
      - name: Install swift-format
        run: brew install swiftformat --quiet
      - name: SwiftLint
        run: swiftlint --strict .
      - name: Swift Format Check
        run: swiftformat --lint-only --base-config .swiftformat.conf . --strict
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    needs: lint
    strategy:
      matrix:
        include:
          - runsOn: macOS-26
            name: "macOS 26, SPM 6.2.0 Test"
    steps:
      - uses: actions/checkout@v4
      - name: Install Swiftly And Swift
        run: |
          curl -L https://download.swift.org/swiftly/darwin/swiftly.pkg > swiftly.pkg
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory

          ~/.swiftly/bin/swiftly init

          . "$HOME/.swiftly/env.sh"
          hash -r

          swiftly install --use --assume-yes
          swiftly link --assume-yes

          echo "$HOME/.swiftly/bin" >> $GITHUB_PATH
      - name: Swift Version
        run: which swift && swift --version
      - name: Brew install tools
        run: brew install xcbeautify jemalloc --quiet
      - name: Run Tests
        run: |
          set -o pipefail && swift test --enable-experimental-prebuilts | xcbeautify --renderer github-actions
